# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CHEE asesor educativo
email: hola@asesoreducativo.mx
celular: 686 584 2356
author: Mtro. Carlos Manuel Chee Vázquez
description: >- # this means to ignore newlines until "baseurl:"
  Imparto cursos, diplomados y asesorias en el uso de las TICs. Me especializo en temas relacionados con educación, productividad y alfabetización digital. ¿Te puedo ayudar? Márcame al 686 584 2356.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://asesoreducativo.mx/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: asesoredumx
facebook_username:  asesoredumx
instagram_username: asesoredumx
permalink: pretty
google_analytics: UA-132778445-1

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - a-oferta.md
 - b-cv.md
 - c-contacto.md
 - d-blog.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/